config/routes.rb
Rails.application.routes.draw do
  get "/email_sent/:id", to: "static_pages#email_sent", as: "email_sent"
  get "/home", to: "static_pages#home"
  get "/sign_in", to: "static_pages#sign_in"
  get "/sign_up", to: "static_pages#sign_up"

  resources :companies, only: [:create, :new, :show] do
    resources :jobs, only: [:create, :edit, :new, :show, :update]
  end

  resources :jobs, only: [] do
    resources :applications, only: [:create, :new, :show]
  end

  resources :sign_ins, only: :create
  resources :sign_ups, only: :create
end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :job

  validates :email, presence: true
  validates :job_id, presence: true
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :user

  has_many :jobs

  validates :name, presence: true
  validates :user_id, presence: true
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :company
  belongs_to :user

  has_many :applications

  validates :company_id, presence: true
  validates :title, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :companies
  has_many :jobs

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include TotesCan

  helper_method :can?
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_filter :authenticate_user!

  def create
    application = Application.create(application_params)
    redirect_to job_application_path(application.job_id, application)
  end

  def new
    @application = Application.new(job_id: params[:job_id])
  end

  def show
    @application = Application.find(params[:id])
  end

  private

  def application_params
    params.require(:application).permit(:email, :job_id, :name, :phone)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticate_user!

  def create
    company = Company.new(company_params)
    company.user = current_user
    company.save!
    redirect_to company_path(company)
  end

  def new
    @company = Company.new
  end

  def show
    @company = Company.find(params[:id])
  end

  private

  def company_params
    params.require(:company).permit(:name)
  end
end

app/controllers/concerns/sign_ins_controller.rb
class SignInsController < ApplicationController
  def create
    user = User.find_by(email: params[:email])

    if user.authenticate(params[:password])
      flash[:success] = "You are now signed in"
      redirect_to home_path
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_filter :authenticate_user!

  def create
    job = Job.new(job_params)
    job.user = current_user
    job.save
    redirect_to company_job_path(job.company_id, job)
  end

  def edit
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new(company_id: params[:company_id])
  end

  def show
    @job = Job.find(params[:id])
    authorize! :read, @job
  end

  def update
    job = Job.find(params[:id])
    job.update(job_params)
    redirect_to company_job_path(job.company_id, job)
  end

  private

  def job_params
    params.require(:job).permit(:description, :title, :company_id)
  end
end

app/controllers/sign_ins_controller.rb
class SignInsController < ApplicationController
  def create
    user = User.find_by(email: params[:email])

    if user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success]   = "You are now signed in"
      redirect_to home_path
    end
  end
end

app/controllers/sign_ups_controller.rb
class SignUpsController < ApplicationController
  def create
    user = User.create(
      email: params[:email],
      password: params[:password]
    )
    ApplicationMailer.sign_up(user).deliver_now
    redirect_to email_sent_path(user, { email: user.email })
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def email_sent
    authenticate_guest!

    @user = User.new(email: params[:email])
  end

  def home
    authenticate_user!
  end

  def sign_in
    authenticate_guest!

    if params[:email_confirmed]
      flash[:success] = "Email #{params[:email]} confirmed"
    end
  end

  def sign_up
    authenticate_guest!

    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applications/new.html.erb
<h1>New Application</h1>

<%= form_for [@application.job, @application] do |f| %>
  <%= f.hidden_field :job_id, value: @application.job_id %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </p>
  <p>
    <%= f.submit "Submit" %>
  </p>
<% end %>

app/views/applications/show.html.erb
<h1>Application</h1>

<p>Name:</p>
<p><%= @application.name %></p>
<p>Email:</p>
<p><%= @application.email %></p>
<p>Phone</p>
<p><%= @application.phone %></p>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= form_for @company do |f| %>
  <p>
    <%= f.label :name %>
    <br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.button "Submit" %>
  </p>
<% end %>

app/views/companies/show.html.erb
<h1>Company</h1>

<p>Name:</p>
<p><%= @company.name %></p>

<%= link_to "New Job", new_company_job_path(@company) %>

app/views/jobs/_form.html.erb
<%= form_for [@job.company, @job] do |f| %>
  <%= f.hidden_field :company_id, value: @job.company_id %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit "Submit" %>
  </p>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Job</h1>

<%= render "form" %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render "form" %>

app/views/jobs/show.html.erb
<h1>Job</h1>

<p>Title:</p>
<p><%= @job.title %></p>

<p>Description:</p>
<p><%= @job.description %></p>

<p>
  <%= link_to(
    "New Application",
    new_job_application_path(@job)
  )%>
</p>

<% if can? :update, @job %>
  <p>
    <%= link_to(
      "Edit Job",
      edit_company_job_path(@job.company_id, @job)
    )%>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPlumhire</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if flash[:success] %>
      <%= flash[:success] %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/email_sent.html.erb
<h1>Email sent to <%= @user.email %>

app/views/static_pages/home.html.erb
<h1>Home</h1>

<%= link_to "New Company", new_company_path %>

app/views/static_pages/sign_in.html.erb
<h1>Sign In</h1>

<%= form_tag sign_ins_path do %>
  <p>
    <%= label_tag :email %>
    <%= text_field_tag :email %>
  </p>
  <p>
    <%= label_tag :password %>
    <%= text_field_tag :password %>
  </p>
  <p>
    <%= submit_tag "Submit" %>
  </p>
<% end %>

app/views/static_pages/sign_up.html.erb
<h1>Sign Up</h1>

<%= form_tag sign_ups_path do %>
  <p>
    <%= label_tag :email %>
    <br />
    <%= text_field_tag :email %>
  </p>
  <p>
    <%= label_tag :password %>
    <br />
    <%= text_field_tag :password %>
  </p>
  <p>
    <%= button_tag "Submit" %>
  </p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <p>
    <%= f.label :email %>
    <br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <br />
    <%= f.text_field :password %>
  </p>
  <p>
    <%= f.button "Submit" %>
  </p>
<% end %>